Failure # 1 (occurred at 2024-01-22_14-39-54)
[36mray::ResourceTrainable.train()[39m (pid=106185, ip=10.99.101.133, actor_id=d3198c1aed30f3e4509f5d9601000000, repr=<ray.tune.trainable.util.mh_sim_trainable object at 0x2b5a0ac29250>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adeyemi.n/.conda/envs/bed_allocation_proj/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/home/adeyemi.n/.conda/envs/bed_allocation_proj/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 339, in train
    result = self.step()
             ^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adeyemi.n/MH_Simulation/Inpatient_Bed_Allocation_Optimization/experiments/parameter_tuning/__main__.py", line 25, in step
    self.optim_job.execute_iteration()
  File "/tmp/ray/session_2024-01-22_14-35-59_692432_88581/runtime_resources/working_dir_files/_ray_pkg_5b2cc7bf73a57e42/optimizers/DD_PUSA/DD_PUSA.py", line 289, in execute_iteration
    self.pareto_set, _ = self.mo_ocba(self.pareto_set)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2024-01-22_14-35-59_692432_88581/runtime_resources/working_dir_files/_ray_pkg_5b2cc7bf73a57e42/optimizers/DD_PUSA/DD_PUSA.py", line 157, in mo_ocba
    ) - sol_set.total_replications()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'pareto_set' object has no attribute 'total_replications'
